#  _____       _        _____            _                 _                        _       
# | ____|_ __ (_) ___  | ____|_ __   ___| |__   __ _ _ __ | |_ _ __ ___   ___ _ __ | |_ ___ 
# |  _| | '_ \| |/ __| |  _| | '_ \ / __| '_ \ / _` | '_ \| __| '_ ` _ \ / _ \ '_ \| __/ __|
# | |___| |_) | | (__  | |___| | | | (__| | | | (_| | | | | |_| | | | | |  __/ | | | |_\__ \
# |_____| .__/|_|\___| |_____|_| |_|\___|_| |_|\__,_|_| |_|\__|_| |_| |_|\___|_| |_|\__|___/
#       |_|                                                                                 

# Version 1.0
# Made by: lapisguy

                                                                                      
# There are many features in this skript that regular skript does not have.
# Therefore some addons are required for this plugin to work properly.
# 
# Skript (Bensku Fork) - Base skript plugin, latest supported version.
# SkQuery (Fork) - Required for menus.
# SkMorkaz - Required for enchantment applications on items.
# SkDragon - Required for all abilities with custom particle effects.
# SharpSk - Required for the potion effects application.


options:
# ######################################################################################
#
# Configuration
#
# ######################################################################################

#	PREFIX:

	main prefix: &8[&dSnap&8]
	
	abilities prefix: &8[&cSnap&8]

# ######################################################################################

# 	PERMISSIONS:

	general permission: epicenchant.use

	admin permission: epicenchant.admin

# ######################################################################################

#	ENCHANTMENT MANAGEMENT:

	allow potion enchants: true

	allow custom enchants: true

	allow active enchants: true

	item enchantment limit: 5

# ######################################################################################

#	ENCHANTMENTS:

	ignite percentage chance: 5
	
	confusion percentage chance: 5

	vampire percentage chance: 5
	
	smelt percentage chance: 25
	
# ######################################################################################


	
	
	
	










# .----------------. .----------------. .----------------. .----------------. 
#| .--------------. | .--------------. | .--------------. | .--------------. |
#| |     ______   | | |     ____     | | |  ________    | | |  _________   | |
#| |   .' ___  |  | | |   .'    `.   | | | |_   ___ `.  | | | |_   ___  |  | |
#| |  / .'   \_|  | | |  /  .--.  \  | | |   | |   `. \ | | |   | |_  \_|  | |
#| |  | |         | | |  | |    | |  | | |   | |    | | | | |   |  _|  _   | |
#| |  \ `.___.'\  | | |  \  `--'  /  | | |  _| |___.' / | | |  _| |___/ |  | |
#| |   `._____.'  | | |   `.____.'   | | | |________.'  | | | |_________|  | |
#| |              | | |              | | |              | | |              | |
#| '--------------' | '--------------' | '--------------' | '--------------' |
# '----------------' '----------------' '----------------' '----------------' 

# TRY NOT TO EDIT IT IF YOU DONT KNOW WHAT YOU ARE DOING!

on load:
	if {@allow potion enchants} is true:
		set {epicenchant.potion.enchants.status} to 1
	if {@allow potion enchants} is false:
		set {epicenchant.potion.enchants.status} to 0
	if {@allow custom enchants} is true:
		set {epicenchant.custom.enchants.status} to 1
	if {@allow custom enchants} is false:
		set {epicenchant.custom.enchants.status} to 0
	if {@allow active enchants} is true:
		set {epicenchant.active.enchants.status} to 1
	if {@allow active enchants} is false:
		set {epicenchant.active.enchants.status} to 0

	set {epicenchant.buyenchants.menu.verification} to 0
	if {epicenchant.potion.enchants.status} is 1:
		add 2 to {epicenchant.buyenchants.menu.verification}
	if {epicenchant.custom.enchants.status} is 1:
		add 4 to {epicenchant.buyenchants.menu.verification}
	if {epicenchant.active.enchants.status} is 1:
		add 8 to {epicenchant.buyenchants.menu.verification}

	
on quit:
	if player is in world "Wilderness":	
		set {epicenchant.a.ability.activation.status.%player%} to "&cCurrently Inactive"
		delete {epicenchant.a.ability.%player%}
		
on join:
	if player is in world "Wilderness":	
		set {epicenchant.a.ability.activation.status.%player%} to "&cCurrently Inactive"
		delete {epicenchant.a.ability.%player%}

		if {epicenchant.a.ability.allowswitch.%player%} is not set:
			set {epicenchant.a.ability.allowswitch.%player%} to 0
		
on death:
	if player is in world "Wilderness":	
		set {epicenchant.a.ability.activation.status.%player%} to "&cCurrently Inactive"
		delete {epicenchant.a.ability.%player%}
		
		
command /epicenchant [<text>] [<player>] [<text>] [<text>]:
	aliases: ee, epicenchantments
	trigger:
		if player has permission "{@admin permission}":
			if arg-1 is not set:	
				message "&r"
				message "&7&m-------------&r&8[&6Epic&4Enchants&8]&7&m-------------"
				message ""
				message "&cVersion&8:&4 1.0"
				message ""
				message "&cDo &4/ee help &cto find out more!"
				message ""
				message "&7&m--------------------------------------"
			if arg-1 is set:
				if arg-1 is "help":
					message "&7&m-------------&r&8[&6Epic&4Enchants&8]&7&m-------------"
					message ""
					message "&c&l/ee &eresetcooldown (player)"
					message "&8- &3&oAbility to reset any player's active ability cooldowns!"
					message "&c&l/ee &egivesign"
					message "&8- &3&oGives a sign which can be placed for players to gamble and recieve a random enchantment."
					message ""
					message "&e&oMore commands coming soon!"
					message ""
					message "&7&m--------------------------------------"
				if arg-1 is "resetcooldown":
					if player-argument is not set:
						delete {epicenchant.a.ability.firework.cooldown.%player%}
						delete {epicenchant.a.ability.vanish.cooldown.%player%}
						delete {epicenchant.a.ability.lightning.cooldown.%player%}
						delete {epicenchant.a.ability.zoom.cooldown.%player%}
						delete {epicenchant.a.ability.invincible.cooldown.%player%}
						delete {epicenchant.a.ability.projectile.cooldown.%player%}
						set {epicenchant.a.ability.allowswitch.%player%} to 0
						message "{@main prefix} &aAll your active ability cooldowns have been reset!"
						stop
					else:
						delete {epicenchant.ability.firework.cooldown.%player-argument%}
						delete {epicenchant.ability.vanish.cooldown.%player-argument%}
						delete {epicenchant.ability.lightning.cooldown.%player-argument%}
						delete {epicenchant.ability.zoom.cooldown.%player-argument%}
						delete {epicenchant.ability.invincible.cooldown.%player-argument%}
						delete {epicenchant.ability.projectile.cooldown.%player-argument%}
						set {epicenchant.ability.allowswitch.%player-argument%}  to 0
						message "{@main prefix} &aAll your active ability cooldowns have been reset!" to player-argument
						message "{@main prefix} &aYou have reset all of &2%player-argument%&a's active ability cooldowns!"
						stop
				if arg-1 is "givesign":
					open chest with 1 row named "&4Gambling Signs &c(Admin)" to player
					wait 3 tick
					if name of player's current inventory contains "&4Gambling Signs":
						format slot 0 of player with black stained glass pane with name "&r" with lore "&r" to be unstealable
						format slot 1 of player with black stained glass pane with name "&r" with lore "&r" to be unstealable
						format slot 2 of player with a light blue stained glass pane named "&b&oPotion Enchants &eGambling Sign" with lore "&r||&cClick To Get Sign||&r||&7- &3&oPlace sign for players to recieve random enchantments!||&7- &3&oThis sign can give any Potion Enchantment!||&r||&7Costs Player&8: &3L20 XP" to close then run [execute player command "epicenchant-getgamblesign potion"]
						format slot 3 of player with black stained glass pane with name "&r" with lore "&r" to be unstealable
						format slot 4 of player with a light green stained glass pane named "&a&oCustom Enchants &eGambling Sign" with lore "&r||&cClick To Get Sign||&r||&7- &3&oPlace sign for players to recieve random enchantments!||&7- &3&oThis sign can give any Custom Enchantment!||&r||&7Costs Player&8: &3L65 XP" to close then run [execute player command "epicenchant-getgamblesign custom"]
						format slot 5 of player with black stained glass pane with name "&r" with lore "&r" to be unstealable
						format slot 6 of player with a red stained glass pane named "&4&oActive Enchants &eGambling Sign" with lore "&r||&cClick To Get Sign||&r||&7- &3&oPlace sign for players to recieve random enchantments!||&7- &3&oThis sign can give any Active Enchantment!||&r||&7Costs Player&8: &3L85 XP" to close then run [execute player command "epicenchant-getgamblesign active"]
						format slot 7 of player with black stained glass pane with name "&r" with lore "&r" to be unstealable
						format slot 8 of player with black stained glass pane with name "&r" with lore "&r" to be unstealable
						stop

				if arg-1 is not "help" or "resetcooldown" or "givesign":
					message "{@main prefix} &cIncorrect Usage. Do &4/ebadmin help &cto find out more!"
					stop
							
		else:
			message "{@main prefix} &cYou do not have permission."
			stop

command /epicenchant-getgamblesign [<text>]:
	trigger:
		if player has permission "{@admin permission}":
			if arg-1 is "potion":
				if {epicenchant.potion.enchants.status} is 1:
					give player a sign named "&b&oPotion Enchantment &eGambling Sign" with lore "&r||&cPlace To Setup||&r||&7- &3&oPlace sign for players to recieve random enchantments!||&7- &3&oThis sign can give any Potion Enchantment!||&r||&7Costs Player&8: &3L20 XP"
					stop
				else:
					message "{@main prefix} &cPotion Abilities are currently disabled."
					stop
			if arg-1 is "custom":
				if {epicenchant.custom.enchants.status} is 1:
					give player a sign named "&a&oCustom Enchantment &eGambling Sign" with lore "&r||&cPlace To Setup||&r||&7- &3&oPlace sign for players to recieve random enchantments!||&7- &3&oThis sign can give any Custom Enchantment!||&r||&7Costs Player&8: &3L65 XP"
					stop
				else:
					message "{@main prefix} &cCustom Abilities are currently disabled."
					stop
			if arg-1 is "active":
				if {epicenchant.active.enchants.status} is 1:
					give player a sign named "&4&oActive Enchantment &eGambling Sign" with lore "&r||&cPlace To Setup||&r||&7- &3&oPlace sign for players to recieve random enchantments!||&7- &3&oThis sign can give any Active Enchantment!||&r||&7Costs Player&8: &3L85 XP"
					stop
				else:
					message "{@main prefix} &cActive Abilities are currently disabled."
					stop
			
on place:
	if player's tool is a sign:
		if lore of player's tool contains "&r||&cPlace To Setup||&r||&7- &3&oPlace sign for players to recieve random enchantments!||&7- &3&oThis sign can give any Potion Enchantment!||&r||&7Costs Player&8: &3L20 XP":
			if player has permission "{@admin permission}":
				if {epicenchant.potion.enchants.status} is 1:
					message "{@main prefix} &aGamble Sign has been successfully placed."
					set player's tool to air
					set {epicenchant.gamblesign.%location of event-block%} to 1
					wait 1 second
					message "{@main prefix} &aGambling Sign has been successfully placed."
					set line 1 of event-block to "&1EpicEnch"
					set line 2 of event-block to "Random"
					set line 3 of event-block to "&bPotion Enchant"
					set line 4 of event-block to "&c20 EXP"
					stop
				else:
					cancel event
					message "{@main prefix} &cPotion Abilities are currently disabled."
					stop
			else:
				cancel event
				remove event-item from player's inventory
				message "{@main prefix} &cYou do not have permission to have this item."
				stop
		if lore of player's tool contains "&r||&cPlace To Setup||&r||&7- &3&oPlace sign for players to recieve random enchantments!||&7- &3&oThis sign can give any Custom Enchantment!||&r||&7Costs Player&8: &3L65 XP":
			if player has permission "{@admin permission}":
				if {epicenchant.custom.enchants.status} is 1:
					set player's tool to air
					set {epicenchant.gamblesign.%location of event-block%} to 1
					wait 1 second
					message "{@main prefix} &aGambling Sign has been successfully placed."
					set line 1 of event-block to "&1EpicEnch"
					set line 2 of event-block to "Random"
					set line 3 of event-block to "&aCustom Enchant"
					set line 4 of event-block to "&c65 EXP"
				else:
					cancel event
					message "{@main prefix} &cCustom Abilities are currently disabled."
					stop
			else:
				cancel event
				remove event-item from player's inventory
				message "{@main prefix} &cYou do not have permission to have this item."
				stop
		if lore of player's tool contains "&r||&cPlace To Setup||&r||&7- &3&oPlace sign for players to recieve random enchantments!||&7- &3&oThis sign can give any Active Enchantment!||&r||&7Costs Player&8: &3L85 XP":
			if player has permission "{@admin permission}":
				if {epicenchant.active.enchants.status} is 1:
					set player's tool to air
					set {epicenchant.gamblesign.%location of event-block%} to 1
					wait 1 second
					message "{@main prefix} &aGambling Sign has been successfully placed."
					set line 1 of event-block to "&1EpicEnch"
					set line 2 of event-block to "Random"
					set line 3 of event-block to "&4Active Enchant"
					set line 4 of event-block to "&c85 EXP"
				else:
					cancel event
					message "{@main prefix} &cActive Abilities are currently disabled."
					stop
					
			else:
				cancel event
				remove event-item from player's inventory
				message "{@main prefix} &cYou do not have permission."
				stop
				
on break:
	if event-item is a sign:
		if {epicenchant.gamblesign.%location of event-block%} is 1:
			if player has permission "{@admin permission}":
				if player is sneaking:
					cancel event
					message "{@main prefix} &cGamble Sign has been successfully removed."
					set event-block to air
					delete {epicenchant.gamblesign.%location of event-block%}
					stop
				else:
					message "{@main prefix} &cYou must be sneaking in order to break a gambling sign."
					stop
			else:
				message "{@main prefix} &cYou do not have permission."
				stop
				
on right-click:
	if event-block is a sign:
		if line 1 of event-block contains "&1EpicEnch":
			if line 2 of event-block contains "Random":
				if player has permission "{@general permission}":
					if {epicenchant.gamblesign.%location of event-block%} is 1:
						if {epicenchant.gamblesign.usage.status.%player%} is not set:
							set {epicenchant.gamblesign.usage.status.%player%} to 0
						if {epicenchant.gamblesign.usage.status.%player%} is 0:
							if line 3 of event-block contains "&bPotion Enchant":
								if line 4 of event-block contains "&c20 EXP":
									if {epicenchant.potion.enchants.status} is 1:
										if player's level is greater than or equal to 20:
											reduce player's level by 20
											set {epicenchant.gamblesign.usage.status.%player%} to 1
											message "{@main prefix} &aRandomly selecting a potion enchantment book..."
											wait 3 seconds
											set {_epicenchant.gamblesign.selection.potion.random} to a random integer between 1 and 9
											if {_epicenchant.gamblesign.selection.potion.random} is 1:
												message "{@main prefix} &7&oYou have recieved: &a&nSpeed I&r &7&oenchanted book."
												give enchanted book named "&bSpeed I" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Helmet||&c- Any Chestplate||&c- Any Leggings||&c- Any Boots" to player
											if {_epicenchant.gamblesign.selection.potion.random} is 2:
												message "{@main prefix} &7&oYou have recieved: &a&nSpeed II&r &7&oenchanted book."
												give enchanted book named "&bSpeed II" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Helmet||&c- Any Chestplate||&c- Any Leggings||&c- Any Boots" to player
											if {_epicenchant.gamblesign.selection.potion.random} is 3:
												message "{@main prefix} &7&oYou have recieved: &a&nStrength I&r &7&oenchanted book."
												give enchanted book named "&bStrength I" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Helmet||&c- Any Chestplate||&c- Any Leggings||&c- Any Boots" to player
											if {_epicenchant.gamblesign.selection.potion.random} is 4:
												message "{@main prefix} &7&oYou have recieved: &a&nStrength II&r &7&oenchanted book."
												give enchanted book named "&bStrength II" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Helmet||&c- Any Chestplate||&c- Any Leggings||&c- Any Boots" to player
											if {_epicenchant.gamblesign.selection.potion.random} is 5:
												message "{@main prefix} &7&oYou have recieved: &a&nJump Boost I&r &7&oenchanted book."
												give enchanted book named "&bJump Boost I" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Helmet||&c- Any Chestplate||&c- Any Leggings||&c- Any Boots" to player
											if {_epicenchant.gamblesign.selection.potion.random} is 6:
												message "{@main prefix} &7&oYou have recieved: &a&nJump Boost II&r &7&oenchanted book."
												give enchanted book named "&bJump Boost II" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Helmet||&c- Any Chestplate||&c- Any Leggings||&c- Any Boots" to player
											if {_epicenchant.gamblesign.selection.potion.random} is 7:
												message "{@main prefix} &7&oYou have recieved: &a&nFire Resistance I&r &7&oenchanted book."
												give enchanted book named "&bFire Resistance I" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Helmet||&c- Any Chestplate||&c- Any Leggings||&c- Any Boots" to player
											if {_epicenchant.gamblesign.selection.potion.random} is 8:
												message "{@main prefix} &7&oYou have recieved: &a&nWalk Breathing I&r &7&oenchanted book."
												give enchanted book named "&bWater Breathing I" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Helmet||&c- Any Chestplate||&c- Any Leggings||&c- Any Boots" to player
											if {_epicenchant.gamblesign.selection.potion.random} is 9:
												message "{@main prefix} &7&oYou have recieved: &a&nRegeneration I&r &7&oenchanted book."
												give enchanted book named "&bRegeneration I" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Helmet||&c- Any Chestplate||&c- Any Leggings||&c- Any Boots" to player
											set {epicenchant.gamblesign.usage.status.%player%} to 0
											stop
										else:
											message "&cError: &4Not enough XP levels!"
											stop
								
							if line 3 of event-block contains "&aCustom Enchant":
								if line 4 of event-block contains "&c65 EXP":
									if {epicenchant.custom.enchants.status} is 1:
										if player's level is greater than or equal to 65:
											reduce player's level by 65
											set {epicenchant.gamblesign.usage.status.%player%} to 1
											message "{@main prefix} &aRandomly selecting a custom enchantment book..."
											wait 3 seconds
											set {_epicenchant.gamblesign.selection.custom.random} to a random integer between 1 and 9
											if {_epicenchant.gamblesign.selection.custom.random} is 1:
												message "{@main prefix} &7&oYou have recieved: &a&nGravity I&r &7&oenchanted book."
												give enchanted book named "&aGravity I" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Boots" to player
											if {_epicenchant.gamblesign.selection.custom.random} is 2:
												message "{@main prefix} &7&oYou have recieved: &a&nAuto Repair I&r &7&oenchanted book."
												give enchanted book named "&aAuto Repair I" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Helmet||&c- Any Chestplate||&c- Any Leggings||&c- Any Boots" to player
											if {_epicenchant.gamblesign.selection.custom.random} is 3:
												message "{@main prefix} &7&oYou have recieved: &a&nAuto Repair II&r &7&oenchanted book."
												give enchanted book named "&aAuto Repair II" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Helmet||&c- Any Chestplate||&c- Any Leggings||&c- Any Boots" to player
											if {_epicenchant.gamblesign.selection.custom.random} is 4:
												message "{@main prefix} &7&oYou have recieved: &a&nIgnite I&r &7&oenchanted book."
												give enchanted book named "&aIgnite I" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Chestplate" to player
											if {_epicenchant.gamblesign.selection.custom.random} is 5:
												message "{@main prefix} &7&oYou have recieved: &a&nConfusion I&r &7&oenchanted book."
												give enchanted book named "&aConfusion I" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Leggings" to player
											if {_epicenchant.gamblesign.selection.custom.random} is 6:
												message "{@main prefix} &7&oYou have recieved: &a&nVampire I&r &7&oenchanted book."
												give enchanted book named "&aVampire I" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Sword||&c- Any Axe" to player
											if {_epicenchant.gamblesign.selection.custom.random} is 7:
												message "{@main prefix} &7&oYou have recieved: &a&nSmelt I&r &7&oenchanted book."
												give enchanted book named "&aSmelt I" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Pickaxe||&c- Any Axe||&c- Any Shovel" to player
											if {_epicenchant.gamblesign.selection.custom.random} is 8:
												message "{@main prefix} &7&oYou have recieved: &a&nSmelt II&r &7&oenchanted book."
												give enchanted book named "&aSmelt I" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Pickaxe||&c- Any Axe||&c- Any Shovel" to player
											if {_epicenchant.gamblesign.selection.custom.random} is 9:
												message "{@main prefix} &7&oYou have recieved: &a&nExtinguish I&r &7&oenchanted book."
												give enchanted book named "&aExtinguish I" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Chestplate" to player
											set {epicenchant.gamblesign.usage.status.%player%} to 0
											stop
										else:
											message "&cError: &4Not enough XP levels!"
											stop
									
							if line 3 of event-block contains "&4Active Enchant":
								if line 4 of event-block contains "&c85 EXP":
									if {epicenchant.active.enchants.status} is 1:
										if player's level is greater than or equal to 85:
											reduce player's level by 85
											set {epicenchant.gamblesign.usage.status.%player%} to 1
											message "{@main prefix} &aRandomly selecting an active enchantment book..."
											wait 3 seconds
											set {_epicenchant.gamblesign.selection.active.random} to a random integer between 1 and 6
											if {_epicenchant.gamblesign.selection.active.random} is 1:
												message "{@main prefix} &7&oYou have recieved: &a&nFirework I&r &7&oenchanted book."
												give enchanted book named "&4Firework I" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Helmet" to player
											if {_epicenchant.gamblesign.selection.active.random} is 2:
												message "{@main prefix} &7&oYou have recieved: &a&nVanish I&r &7&oenchanted book."
												give enchanted book named "&4Vanish I" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Helmet" to player
											if {_epicenchant.gamblesign.selection.active.random} is 3:
												message "{@main prefix} &7&oYou have recieved: &a&nLightning I&r &7&oenchanted book."
												give enchanted book named "&4Lightning I" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Helmet" to player
											if {_epicenchant.gamblesign.selection.active.random} is 4:
												message "{@main prefix} &7&oYou have recieved: &a&nZoom I&r &7&oenchanted book."
												give enchanted book named "&4Zoom I" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Helmet" to player
											if {_epicenchant.gamblesign.selection.active.random} is 5:
												message "{@main prefix} &7&oYou have recieved: &a&nInvincible I&r &7&oenchanted book."
												give enchanted book named "&4Invincible I" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Helmet" to player
											if {_epicenchant.gamblesign.selection.active.random} is 6:
												message "{@main prefix} &7&oYou have recieved: &a&nProjectile I&r &7&oenchanted book."
												give enchanted book named "&4Projectile I" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Helmet" to player
											set {epicenchant.gamblesign.usage.status.%player%} to 0
											stop
										else:
											message "&cError: &4Not enough XP levels!"
											stop
				
# ---------------------------------------            	
# Purchase menu of all enchantments
# ---------------------------------------

command /buyenchants:
	trigger:
		if player has permission "{@general permission}":
			if {epicenchant.buyenchants.menu.verification} is 0:
				message "{@main prefix} &cAll enchantments have been disabled."
				stop
			else:
				open chest with 1 rows named "&4Enchantment Shop" to player
				wait 3 tick
				if name of player's current inventory contains "&4Enchantment Shop":
					if {epicenchant.buyenchants.menu.verification} is 2:
						format slot 2 of player with a bottle named "&b&lPotion Enchants" with lore "&3&oEnchantments that give potion effects." to close then run [execute player command "buyenchants-submenu potionenchants"]
					if {epicenchant.buyenchants.menu.verification} is 4:
						format slot 2 of player with a ender pearl named "&a&lCustom Enchants" with lore "&3&oEnchantments that give unique abilities." to close then run [execute player command "buyenchants-submenu customenchants"]
					if {epicenchant.buyenchants.menu.verification} is 6:
						format slot 2 of player with a bottle named "&b&lPotion Enchants" with lore "&3&oEnchantments that give potion effects." to close then run [execute player command "buyenchants-submenu potionenchants"]
						format slot 4 of player with a ender pearl named "&a&lCustom Enchants" with lore "&3&oEnchantments that give unique abilities." to close then run [execute player command "buyenchants-submenu customenchants"]
					if {epicenchant.buyenchants.menu.verification} is 8:
						format slot 2 of player with a beacon named "&4&lActive Enchants" with lore "&3&oEnchantments that give unique activation abilities." to close then run [execute player command "buyenchants-submenu activeenchants"]
					if {epicenchant.buyenchants.menu.verification} is 10:
						format slot 2 of player with a bottle named "&b&lPotion Enchants" with lore "&3&oEnchantments that give potion effects." to close then run [execute player command "buyenchants-submenu potionenchants"]
						format slot 4 of player with a beacon named "&4&lActive Enchants" with lore "&3&oEnchantments that give unique activation abilities." to close then run [execute player command "buyenchants-submenu activeenchants"]
					if {epicenchant.buyenchants.menu.verification} is 12:
						format slot 2 of player with a ender pearl named "&a&lCustom Enchants" with lore "&3&oEnchantments that give unique abilities." to close then run [execute player command "buyenchants-submenu customenchants"]
						format slot 4 of player with a beacon named "&4&lActive Enchants" with lore "&3&oEnchantments that give unique activation abilities." to close then run [execute player command "buyenchants-submenu activeenchants"]
					if {epicenchant.buyenchants.menu.verification} is 14:
						format slot 2 of player with a bottle named "&b&lPotion Enchants" with lore "&3&oEnchantments that give potion effects." to close then run [execute player command "buyenchants-submenu potionenchants"]
						format slot 4 of player with a ender pearl named "&a&lCustom Enchants" with lore "&3&oEnchantments that give unique abilities." to close then run [execute player command "buyenchants-submenu customenchants"]
						format slot 6 of player with a beacon named "&4&lActive Enchants" with lore "&3&oEnchantments that give unique activation abilities." to close then run [execute player command "buyenchants-submenu activeenchants"]
					loop integers between 0 and 8:
						if slot loop-integer of player's current inventory is air:
							format slot loop-integer of player with black stained glass pane named "&r" with lore "&r" to be unstealable
		else:
			message "{@main prefix} &cYou do not have permission."
			stop

command /buyenchants-submenu [<text>]:
	trigger:
		if player has permission "{@general permission}":
			if {epicenchant.potion.enchants.status} is 1:
				if arg-1 is "potionenchants":
					wait 3 tick
					open chest with 6 rows named "&b&lPotion Enchants" to player
					if name of player's current inventory contains "&b&lPotion Enchants":
						format slot 10 of player with sugar named "&6Ench &8- &b&lSpeed" with lore "&3&oInfinite speed while wearing armor with this enchantment.||&r||&c&oClick for more options." to close then run [execute player command "buyenchants-submenu speed"]
						format slot 11 of player with blaze powder named "&6Ench &8- &5&lStrength" with lore "&3&oInfinite strength while wearing armor with this enchantment.||&r||&c&oClick for more options." to close then run [execute player command "buyenchants-submenu strength"]
						format slot 12 of player with a rabbit foot named "&6Ench &8- &a&lJump Boost" with lore "&3&oInfinite jump boost while wearing armor with this enchantment.||&r||&c&oClick for more options." to close then run [execute player command "buyenchants-submenu jumpboost"]
						format slot 13 of player with a magma cream named "&6Ench &8- &6&lFire Resistance" with lore "&3&oInfinite fire resistance while wearing armor with this enchantment.||&r||&c&oClick for more options." to close then run [execute player command "buyenchants-submenu fireresistance"]
						format slot 14 of player with a fish named "&6Ench &8- &1&lWater Breathing" with lore "&3&oInfinite water breathing while wearing armor with this enchantment.||&r||&c&oClick for more options." to close then run [execute player command "buyenchants-submenu waterbreathing"]
						format slot 15 of player with a ghast tear named "&6Ench &8- &d&lRegeneration" with lore "&3&oInfinite regeneration while wearing armor with this enchantment.||&r||&c&oClick for more options." to close then run [execute player command "buyenchants-submenu regeneration"]			

				if arg-1 is "speed":
					wait 3 tick
					open chest with 6 rows named "&b&lSpeed" to player
					if name of player's current inventory is "&b&lSpeed":
						format slot 4 of player with a barrier named "&c&lEXIT" with lore "&r" to close
						format slot 13 of player with a black stained glass named "&r" with lore "&r" to be unstealable
						format slot 22 of player with a black stained glass named "&r" with lore "&r" to be unstealable
						format slot 31 of player with a black stained glass named "&r" with lore "&r" to be unstealable
						format slot 40 of player with a black stained glass named "&r" with lore "&r" to be unstealable
						format slot 49 of player with a black stained glass named "&r" with lore "&r" to be unstealable

						# 1Speed

						format slot 1 of player with light blue stained glass named "&r" with lore "&r" to be unstealable
						format slot 9 of player with light blue stained glass named "&r" with lore "&r" to be unstealable
						format slot 10 of player with light blue stained glass named "&r" with lore "&r" to be unstealable
						format slot 19 of player with light blue stained glass named "&r" with lore "&r" to be unstealable
						format slot 28 of player with light blue stained glass named "&r" with lore "&r" to be unstealable
						format slot 36 of player with light blue stained glass named "&r" with lore "&r" to be unstealable
						format slot 37 of player with light blue stained glass named "&r" with lore "&r" to be unstealable
						format slot 38 of player with light blue stained glass named "&r" with lore "&r" to be unstealable

						# 2Speed

						format slot 6 of player with light blue stained glass named "&r" with lore "&r" to be unstealable
						format slot 7 of player with light blue stained glass named "&r" with lore "&r" to be unstealable
						format slot 8 of player with light blue stained glass named "&r" with lore "&r" to be unstealable
						format slot 17 of player with light blue stained glass named "&r" with lore "&r" to be unstealable
						format slot 25 of player with light blue stained glass named "&r" with lore "&r" to be unstealable
						format slot 33 of player with light blue stained glass named "&r" with lore "&r" to be unstealable
						format slot 42 of player with light blue stained glass named "&r" with lore "&r" to be unstealable
						format slot 43 of player with light blue stained glass named "&r" with lore "&r" to be unstealable 
						format slot 44 of player with light blue stained glass named "&r" with lore "&r" to be unstealable

						# Speed Books
						format slot 46 of player with sugar named "&6Ench &8- &b&lSpeed I" with lore "&7Cost: &a&n20 XP Levels||&r||&7Can Be Applied To&8:||&c- Any Helmet||&c- Any Chestplate||&c- Any Leggings||&c- Any Boots" to close then run [execute player command "buyenchants-buy speedI"]
						format slot 52 of player with sugar named "&6Ench &8- &b&lSpeed II" with lore "&7Cost: &a&n23 XP Levels||&r||&7Can Be Applied To&8:||&c- Any Helmet||&c- Any Chestplate||&c- Any Leggings||&c- Any Boots" to close then run [execute player command "buyenchants-buy speedII"]
					
				if arg-1 is "strength":
					wait 3 tick
					open chest with 6 rows named "&5&lStrength" to player
					if name of player's current inventory contains "&5&lStrength":
						format slot 4 of player with a barrier named "&c&lEXIT" with lore "&r" to close
						format slot 13 of player with a black stained glass named "&r" with lore "&r" to be unstealable
						format slot 22 of player with a black stained glass named "&r" with lore "&r" to be unstealable
						format slot 31 of player with a black stained glass named "&r" with lore "&r" to be unstealable
						format slot 40 of player with a black stained glass named "&r" with lore "&r" to be unstealable
						format slot 49 of player with a black stained glass named "&r" with lore "&r" to be unstealable

						# 1Strength

						format slot 1 of player with purple stained glass named "&r" with lore "&r" to be unstealable
						format slot 9 of player with purple stained glass named "&r" with lore "&r" to be unstealable
						format slot 10 of player with purple stained glass named "&r" with lore "&r" to be unstealable
						format slot 19 of player with purple stained glass named "&r" with lore "&r" to be unstealable
						format slot 28 of player with purple stained glass named "&r" with lore "&r" to be unstealable
						format slot 36 of player with purple stained glass named "&r" with lore "&r" to be unstealable
						format slot 37 of player with purple stained glass named "&r" with lore "&r" to be unstealable
						format slot 38 of player with purple stained glass named "&r" with lore "&r" to be unstealable

						# 2Strength

						format slot 6 of player with purple stained glass named "&r" with lore "&r" to be unstealable
						format slot 7 of player with purple stained glass named "&r" with lore "&r" to be unstealable
						format slot 8 of player with purple stained glass named "&r" with lore "&r" to be unstealable
						format slot 17 of player with purple stained glass named "&r" with lore "&r" to be unstealable
						format slot 25 of player with purple stained glass named "&r" with lore "&r" to be unstealable
						format slot 33 of player with purple stained glass named "&r" with lore "&r" to be unstealable
						format slot 42 of player with purple stained glass named "&r" with lore "&r" to be unstealable
						format slot 43 of player with purple stained glass named "&r" with lore "&r" to be unstealable 
						format slot 44 of player with purple stained glass named "&r" with lore "&r" to be unstealable

						# Strength Books
						format slot 46 of player with blaze powder named "&6Ench &8- &5&lStrength I" with lore "&7Cost: &a&n20 XP Levels||&r||&7Can Be Applied To&8:||&c- Any Helmet||&c- Any Chestplate||&c- Any Leggings||&c- Any Boots" to close then run [execute player command "buyenchants-buy strengthI"]
						format slot 52 of player with blaze powder named "&6Ench &8- &5&lStrength II" with lore "&7Cost: &a&n23 XP Levels||&r||&7Can Be Applied To&8:||&c- Any Helmet||&c- Any Chestplate||&c- Any Leggings||&c- Any Boots" to close then run [execute player command "buyenchants-buy strengthII"]

				if arg-1 is "jumpboost":
					wait 3 tick
					open chest with 6 rows named "&a&lJump Boost" to player
					if name of player's current inventory contains "&a&lJump Boost":
						format slot 4 of player with a barrier named "&c&lEXIT" with lore "&r" to close
						format slot 13 of player with a black stained glass named "&r" with lore "&r" to be unstealable
						format slot 22 of player with a black stained glass named "&r" with lore "&r" to be unstealable
						format slot 31 of player with a black stained glass named "&r" with lore "&r" to be unstealable
						format slot 40 of player with a black stained glass named "&r" with lore "&r" to be unstealable
						format slot 49 of player with a black stained glass named "&r" with lore "&r" to be unstealable

						# 1JumpBoost

						format slot 1 of player with light green stained glass named "&r" with lore "&r" to be unstealable
						format slot 9 of player with light green stained glass named "&r" with lore "&r" to be unstealable
						format slot 10 of player with light green stained glass named "&r" with lore "&r" to be unstealable
						format slot 19 of player with light green stained glass named "&r" with lore "&r" to be unstealable
						format slot 28 of player with light green stained glass named "&r" with lore "&r" to be unstealable
						format slot 36 of player with light green stained glass named "&r" with lore "&r" to be unstealable
						format slot 37 of player with light green stained glass named "&r" with lore "&r" to be unstealable
						format slot 38 of player with light green stained glass named "&r" with lore "&r" to be unstealable

						# 2JumpBoost

						format slot 6 of player with light green stained glass named "&r" with lore "&r" to be unstealable
						format slot 7 of player with light green stained glass named "&r" with lore "&r" to be unstealable
						format slot 8 of player with light green stained glass named "&r" with lore "&r" to be unstealable
						format slot 17 of player with light green stained glass named "&r" with lore "&r" to be unstealable
						format slot 25 of player with light green stained glass named "&r" with lore "&r" to be unstealable
						format slot 33 of player with light green stained glass named "&r" with lore "&r" to be unstealable
						format slot 42 of player with light green stained glass named "&r" with lore "&r" to be unstealable
						format slot 43 of player with light green stained glass named "&r" with lore "&r" to be unstealable 
						format slot 44 of player with light green stained glass named "&r" with lore "&r" to be unstealable

						# JumpBoost Books
						format slot 46 of player with a rabbit foot named "&6Ench &8- &a&lJump Boost I" with lore "&7Cost: &a&n20 XP Levels||&r||&7Can Be Applied To&8:||&c- Any Helmet||&c- Any Chestplate||&c- Any Leggings||&c- Any Boots" to close then run [execute player command "buyenchants-buy jumpboostI"]
						format slot 52 of player with a rabbit foot named "&6Ench &8- &a&lJump Boost II" with lore "&7Cost: &a&n23 XP Levels||&r||&7Can Be Applied To&8:||&c- Any Helmet||&c- Any Chestplate||&c- Any Leggings||&c- Any Boots" to close then run [execute player command "buyenchants-buy jumpboostII"]

				if arg-1 is "fireresistance":
					wait 3 tick
					open chest with 6 rows named "&6&lFire Resistance" to player
					if name of player's current inventory contains "&6&lFire Resistance":
						format slot 4 of player with a barrier named "&c&lEXIT" with lore "&r" to close
						format slot 13 of player with a black stained glass named "&r" with lore "&r" to be unstealable
						format slot 22 of player with a black stained glass named "&r" with lore "&r" to be unstealable
						format slot 31 of player with a black stained glass named "&r" with lore "&r" to be unstealable
						format slot 40 of player with a black stained glass named "&r" with lore "&r" to be unstealable
						format slot 49 of player with a black stained glass named "&r" with lore "&r" to be unstealable

						# 1FireResistance

						format slot 1 of player with orange stained glass named "&r" with lore "&r" to be unstealable
						format slot 9 of player with orange stained glass named "&r" with lore "&r" to be unstealable
						format slot 10 of player with orange stained glass named "&r" with lore "&r" to be unstealable
						format slot 19 of player with orange stained glass named "&r" with lore "&r" to be unstealable
						format slot 28 of player with orange stained glass named "&r" with lore "&r" to be unstealable
						format slot 36 of player with orange stained glass named "&r" with lore "&r" to be unstealable
						format slot 37 of player with orange stained glass named "&r" with lore "&r" to be unstealable
						format slot 38 of player with orange stained glass named "&r" with lore "&r" to be unstealable

						# QuestionMark
						format slot 7 of player with orange stained glass named "&r" with lore "&r" to be unstealable
						format slot 15 of player with orange stained glass named "&r" with lore "&r" to be unstealable
						format slot 17 of player with orange stained glass named "&r" with lore "&r" to be unstealable
						format slot 26 of player with orange stained glass named "&r" with lore "&r" to be unstealable
						format slot 34 of player with orange stained glass named "&r" with lore "&r" to be unstealable
						format slot 52 of player with orange stained glass named "&r" with lore "&r" to be unstealable

						# FireResistance Books
						format slot 46 of player with a magma cream named "&6Ench &8- &6&lFire Resistance I" with lore "&7Cost: &a&n23 XP Levels||&r||&7Can Be Applied To&8:||&c- Any Helmet||&c- Any Chestplate||&c- Any Leggings||&c- Any Boots" to close then run [execute player command "buyenchants-buy fireresistanceI"]

				if arg-1 is "waterbreathing":
					wait 3 tick
					open chest with 6 rows named "&1&lWater Breathing" to player
					if name of player's current inventory contains "&1&lWater Breathing":
						format slot 4 of player with a barrier named "&c&lEXIT" with lore "&r" to close
						format slot 13 of player with a black stained glass named "&r" with lore "&r" to be unstealable
						format slot 22 of player with a black stained glass named "&r" with lore "&r" to be unstealable
						format slot 31 of player with a black stained glass named "&r" with lore "&r" to be unstealable
						format slot 40 of player with a black stained glass named "&r" with lore "&r" to be unstealable
						format slot 49 of player with a black stained glass named "&r" with lore "&r" to be unstealable

						# 1WaterBreathing

						format slot 1 of player with blue stained glass named "&r" with lore "&r" to be unstealable
						format slot 9 of player with blue stained glass named "&r" with lore "&r" to be unstealable
						format slot 10 of player with blue stained glass named "&r" with lore "&r" to be unstealable
						format slot 19 of player with blue stained glass named "&r" with lore "&r" to be unstealable
						format slot 28 of player with blue stained glass named "&r" with lore "&r" to be unstealable
						format slot 36 of player with blue stained glass named "&r" with lore "&r" to be unstealable
						format slot 37 of player with blue stained glass named "&r" with lore "&r" to be unstealable
						format slot 38 of player with blue stained glass named "&r" with lore "&r" to be unstealable

						# QuestionMark
						format slot 7 of player with blue stained glass named "&r" with lore "&r" to be unstealable
						format slot 15 of player with blue stained glass named "&r" with lore "&r" to be unstealable
						format slot 17 of player with blue stained glass named "&r" with lore "&r" to be unstealable
						format slot 26 of player with blue stained glass named "&r" with lore "&r" to be unstealable
						format slot 34 of player with blue stained glass named "&r" with lore "&r" to be unstealable
						format slot 52 of player with blue stained glass named "&r" with lore "&r" to be unstealable

						# WaterBreathing Books
						format slot 46 of player with a fish named "&6Ench &8- &1&lWater Breathing I" with lore "&7Cost: &a&n23 XP Levels||&r||&7Can Be Applied To&8:||&c- Any Helmet||&c- Any Chestplate||&c- Any Leggings||&c- Any Boots" to close then run [execute player command "buyenchants-buy waterbreathingI"]

				if arg-1 is "regeneration":
					wait 3 tick
					open chest with 6 rows named "&d&lRegeneration" to player
					if name of player's current inventory contains "&d&lRegeneration":
						format slot 4 of player with a barrier named "&c&lEXIT" with lore "&r" to close
						format slot 13 of player with a black stained glass named "&r" with lore "&r" to be unstealable
						format slot 22 of player with a black stained glass named "&r" with lore "&r" to be unstealable
						format slot 31 of player with a black stained glass named "&r" with lore "&r" to be unstealable
						format slot 40 of player with a black stained glass named "&r" with lore "&r" to be unstealable
						format slot 49 of player with a black stained glass named "&r" with lore "&r" to be unstealable

						# 1Regeneration
						
						format slot 1 of player with pink stained glass named "&r" with lore "&r" to be unstealable
						format slot 9 of player with pink stained glass named "&r" with lore "&r" to be unstealable
						format slot 10 of player with pink stained glass named "&r" with lore "&r" to be unstealable
						format slot 19 of player with pink stained glass named "&r" with lore "&r" to be unstealable
						format slot 28 of player with pink stained glass named "&r" with lore "&r" to be unstealable
						format slot 36 of player with pink stained glass named "&r" with lore "&r" to be unstealable
						format slot 37 of player with pink stained glass named "&r" with lore "&r" to be unstealable
						format slot 38 of player with pink stained glass named "&r" with lore "&r" to be unstealable

						# QuestionMark
						format slot 7 of player with pink stained glass named "&r" with lore "&r" to be unstealable
						format slot 15 of player with pink stained glass named "&r" with lore "&r" to be unstealable
						format slot 17 of player with pink stained glass named "&r" with lore "&r" to be unstealable
						format slot 26 of player with pink stained glass named "&r" with lore "&r" to be unstealable
						format slot 34 of player with pink stained glass named "&r" with lore "&r" to be unstealable
						format slot 52 of player with pink stained glass named "&r" with lore "&r" to be unstealable

						# Regeneration Books
						format slot 46 of player with a ghast tear named "&6Ench &8- &d&lRegeneration I" with lore "&7Cost: &a&n23 XP Levels||&r||&7Can Be Applied To&8:||&c- Any Helmet||&c- Any Chestplate||&c- Any Leggings||&c- Any Boots" to close then run [execute player command "buyenchants-buy regenerationI"]

			if {epicenchant.custom.enchants.status} is 1:
				if arg-1 is "customenchants":
					wait 3 tick
					open chest with 6 rows named "&a&lCustom Enchants" to player
					if name of player's current inventory contains "&a&lCustom Enchants":
						format slot 10 of player with a compass named "&6Ench &8- &5&lGravity I" with lore "&3&oOn death, launch all players and mobs in a 7 block radius up into the sky!||&r||&7Can Be Applied To&8:||&c- Any Boots" to close then run [execute player command "buyenchants-buy gravityI"]
						format slot 11 of player with a anvil named "&6Ench &8- &2&lAuto Repair" with lore "&3&oAbility for your armour to repair itself over time!||&r||&c&oClick for more options." to close then run [execute player command "buyenchants-submenu autorepair"]
						format slot 12 of player with a flint and steel named "&6Ench &8- &4&lIgnite I" with lore "&3&oChance to make your attacker combust!||&r||&7Cost: &a&n25 XP Levels||&r||&7Can Be Applied To&8:||&c- Any Chestplate" to close then run [execute player command "buyenchants-buy igniteI"]
						format slot 13 of player with a spider eye named "&6Ench &8- &8&lConfusion I" with lore "&3&oChance to give your attacker confusion and gain speed!||&r||&7Cost: &a&n25 XP Levels||&r||&7Can Be Applied To&8:||&c- Any Leggings" to close then run [execute player command "buyenchants-buy confusionI"]
						format slot 14 of player with a redstone dust named "&6Ench &8- &c&lVampire I" with lore "&3&oChance to steal one of your victims's hearts!||&r||&7Cost: &a&n25 XP Levels||&r||&7Can Be Applied To&8:||&c- Any Sword||&c- Any Axe" to close then run [execute player command "buyenchants-buy vampireI"]
						format slot 15 of player with a charcoal named "&6Ench &8- &e&lSmelt" with lore "&3&oChance to drop a smelted state of a smeltable block!||&r||&cClick for more options." to close then run [execute player command "buyenchants-submenu smelt"]
						format slot 16 of player with a water bucket named "&6Ench &8- &3&lExtinguish I" with lore "&3&oReduces the amount of damage ignite does to you!||&r||&7Cost: &a&n25 XP Levels||&r||&7Can Be Applied To&8:||&c- Any Chestplate" to close then run [execute player command "buyenchants-buy extinguishI"]

				if arg-1 is "autorepair":
					wait 3 tick
					open chest with 6 rows named "&2&lAuto Repair" to player
					if name of player's current inventory contains "&2&lAuto Repair":
						format slot 4 of player with a barrier named "&c&lEXIT" with lore "&r" to close
						format slot 13 of player with a black stained glass named "&r" with lore "&r" to be unstealable
						format slot 22 of player with a black stained glass named "&r" with lore "&r" to be unstealable
						format slot 31 of player with a black stained glass named "&r" with lore "&r" to be unstealable
						format slot 40 of player with a black stained glass named "&r" with lore "&r" to be unstealable
						format slot 49 of player with a black stained glass named "&r" with lore "&r" to be unstealable

						# 1AutoRepair

						format slot 1 of player with green stained glass named "&r" with lore "&r" to be unstealable
						format slot 9 of player with green stained glass named "&r" with lore "&r" to be unstealable
						format slot 10 of player with green stained glass named "&r" with lore "&r" to be unstealable
						format slot 19 of player with green stained glass named "&r" with lore "&r" to be unstealable
						format slot 28 of player with green stained glass named "&r" with lore "&r" to be unstealable
						format slot 36 of player with green stained glass named "&r" with lore "&r" to be unstealable
						format slot 37 of player with green stained glass named "&r" with lore "&r" to be unstealable
						format slot 38 of player with green stained glass named "&r" with lore "&r" to be unstealable

						# 2AutoRepair

						format slot 6 of player with green stained glass named "&r" with lore "&r" to be unstealable
						format slot 7 of player with green stained glass named "&r" with lore "&r" to be unstealable
						format slot 8 of player with green stained glass named "&r" with lore "&r" to be unstealable
						format slot 17 of player with green stained glass named "&r" with lore "&r" to be unstealable
						format slot 25 of player with green stained glass named "&r" with lore "&r" to be unstealable
						format slot 33 of player with green stained glass named "&r" with lore "&r" to be unstealable
						format slot 42 of player with green stained glass named "&r" with lore "&r" to be unstealable
						format slot 43 of player with green stained glass named "&r" with lore "&r" to be unstealable 
						format slot 44 of player with green stained glass named "&r" with lore "&r" to be unstealable

						# AutoRepair Books
						format slot 46 of player with an anvil named "&6Ench &8- &2&lAuto Repair I" with lore "&3&oAbility for your armour to repair itself over time!||&r||&7Cost: &a&n25 XP Levels||&r||&7Can Be Applied To&8:||&c- Any Helmet||&c- Any Chestplate||&c- Any Leggings||&c- Any Boots" to close then run [execute player command "buyenchants-buy autorepairI"]
						format slot 52 of player with an anvil named "&6Ench &8- &2&lAuto Repair II" with lore "&3&oAbility for your armour to repair itself faster!||&r||&7Cost: &a&n35 XP Levels||&r||&7Can Be Applied To&8:||&c- Any Helmet||&c- Any Chestplate||&c- Any Leggings||&c- Any Boots" to close then run [execute player command "buyenchants-buy autorepairII"]

				if arg-1 is "smelt":
					wait 3 tick
					open chest with 6 rows named "&e&lSmelt" to player
					if name of player's current inventory contains "&e&lSmelt":
						format slot 4 of player with a barrier named "&c&lEXIT" with lore "&r" to close
						format slot 13 of player with a black stained glass named "&r" with lore "&r" to be unstealable
						format slot 22 of player with a black stained glass named "&r" with lore "&r" to be unstealable
						format slot 31 of player with a black stained glass named "&r" with lore "&r" to be unstealable
						format slot 40 of player with a black stained glass named "&r" with lore "&r" to be unstealable
						format slot 49 of player with a black stained glass named "&r" with lore "&r" to be unstealable

						# 1AutoRepair

						format slot 1 of player with yellow stained glass named "&r" with lore "&r" to be unstealable
						format slot 9 of player with yellow stained glass named "&r" with lore "&r" to be unstealable
						format slot 10 of player with yellow stained glass named "&r" with lore "&r" to be unstealable
						format slot 19 of player with yellow stained glass named "&r" with lore "&r" to be unstealable
						format slot 28 of player with yellow stained glass named "&r" with lore "&r" to be unstealable
						format slot 36 of player with yellow stained glass named "&r" with lore "&r" to be unstealable
						format slot 37 of player with yellow stained glass named "&r" with lore "&r" to be unstealable
						format slot 38 of player with yellow stained glass named "&r" with lore "&r" to be unstealable

						# 2AutoRepair

						format slot 6 of player with yellow stained glass named "&r" with lore "&r" to be unstealable
						format slot 7 of player with yellow stained glass named "&r" with lore "&r" to be unstealable
						format slot 8 of player with yellow stained glass named "&r" with lore "&r" to be unstealable
						format slot 17 of player with yellow stained glass named "&r" with lore "&r" to be unstealable
						format slot 25 of player with yellow stained glass named "&r" with lore "&r" to be unstealable
						format slot 33 of player with yellow stained glass named "&r" with lore "&r" to be unstealable
						format slot 42 of player with yellow stained glass named "&r" with lore "&r" to be unstealable
						format slot 43 of player with yellow stained glass named "&r" with lore "&r" to be unstealable 
						format slot 44 of player with yellow stained glass named "&r" with lore "&r" to be unstealable

						# AutoRepair Books
						format slot 46 of player with an charcoal named "&6Ench &8- &e&lSmelt I" with lore "&3&o{@smelt percentage chance}%% Chance to drop a smelted state of a smeltable block!||&7Cost: &a&n25 XP Levels||&r||&7Can Be Applied To&8:||&c- Any Pickaxe||&c- Any Axe||&c- Any Shovel" to close then run [execute player command "buyenchants-buy smeltI"]
						format slot 52 of player with an charcoal named "&6Ench &8- &e&lSmelt II" with lore "&3&oDrops smelted state of a smeltable block all the time!||&r||&7Cost: &a&n120 XP Levels||&r||&7Can Be Applied To&8:||&c- Any Pickaxe||&c- Any Axe||&c- Any Shovel" to close then run [execute player command "buyenchants-buy smeltII"]						

			if {epicenchant.active.enchants.status} is 1:
				if arg-1 is "activeenchants":
					wait 3 tick
					open chest with 6 rows named "&4&lActive Enchants" to player
					if name of player's current inventory contains "&4&lActive Enchants":
						format slot 10 of player with a firework rocket named "&6Ench &8- &6&lFirework I" with lore "&3&oAbility to blast in the air.||&c3 minute cooldown||&r||&7Cost: &a&n35 XP Levels||&r||&7Can Be Applied To&8:||&c- Any Helmet" to close then run [execute player command "buyenchants-buy fireworkI"]
						format slot 11 of player with a golden carrot named "&6Ench &8- &9&lVanish I" with lore "&3&oAbility to go invisible for 5 seconds.||&c5 minute cooldown||&r||&7Cost: &a&n35 XP Levels||&r||&7Can Be Applied To&8:||&c- Any Helmet" to close then run [execute player command "buyenchants-buy vanishI"]
						format slot 12 of player with a nether star named "&6Ench &8- &e&lLightning I" with lore "&3&oAbility to strike the surrounding mobs and players with lightning.||&c3 minute cooldown||&r||&7Cost: &a&n35 XP Levels||&r||&7Can Be Applied To&8:||&c- Any Helmet" to close then run [execute player command "buyenchants-buy lightningI"]
						format slot 13 of player with a compass named "&6Ench &8- &b&lZoom I" with lore "&3&oAbility to travel faster than sound for 2 seconds.||&c5 minute cooldown||&r||&7Cost: &a&n35 XP Levels||&r||&7Can Be Applied To&8:||&c- Any Helmet" to close then run [execute player command "buyenchants-buy zoomI"]
						format slot 14 of player with a enchanted golden apple named "&6Ench &8- &d&lInvincible I" with lore "&3&oAbility to temporarily be immune to all damage for 5 seconds.||&c5 minute cooldown||&r||&7Cost: &a&n35 XP Levels||&r||&7Can Be Applied To&8:||&c- Any Helmet" to close then run [execute player command "buyenchants-buy invincibleI"]
						format slot 15 of player with a arrow named "&6Ench &8- &2&lProjectile I" with lore "&3&oAbility to travel like a projectile.||&c3 minute cooldown||&r||&7Cost: &a&n35 XP Levels||&r||&7Can Be Applied To&8:||&c- Any Helmet" to close then run [execute player command "buyenchants-buy projectileI"]
			loop integers between 0 and 53:
				if slot loop-integer of player's current inventory is air:
					format slot loop-integer of player with white stained glass pane named "&r" with lore "&r" to be unstealable
		else:
			message "{@main prefix} &cYou do not have permission."
			stop

command /buyenchants-buy [<text>]:
	trigger:
		if player has permission "{@general permission}":
		
# Potion Abilities Purchase

			if {epicenchant.potion.enchants.status} is 1:	
				if arg-1 is "speedI":
					if player's level is greater than or equal to 20:
						give enchanted book named "&bSpeed I" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Helmet||&c- Any Chestplate||&c- Any Leggings||&c- Any Boots" to player
						message "&7&oSucessfully purchased &a&nSpeed I&r &7&oenchantment book!" to player
						reduce player's level by 20
						stop
					if player's level is less than 20:
						message "&cError: &4Not enough XP levels!"
						stop
				if arg-1 is "strengthI":
					if player's level is greater than or equal to 20:
						give enchanted book named "&bStrength I" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Helmet||&c- Any Chestplate||&c- Any Leggings||&c- Any Boots" to player
						message "&7&oSucessfully purchased &a&nStrength I&r &7&oenchantment book!" to player
						reduce player's level by 20
						stop
					if player's level is less than 20:
						message "&cError: &4Not enough XP levels!"
						stop
				if arg-1 is "jumpboostI":
					if player's level is greater than or equal to 20:
						give enchanted book named "&bJump Boost I" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Helmet||&c- Any Chestplate||&c- Any Leggings||&c- Any Boots" to player
						message "&7&oSucessfully purchased &a&nJump Boost I&r &7&oenchantment book!" to player
						reduce player's level by 20
						stop
					if player's level is less than 20:
						message "&cError: &4Not enough XP levels!"
						stop
				if arg-1 is "fireresistanceI":
					if player's level is greater than or equal to 23:
						give enchanted book named "&bFire Resistance I" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Helmet||&c- Any Chestplate||&c- Any Leggings||&c- Any Boots" to player
						message "&7&oSucessfully purchased &a&nFire Resistance I&r &7&oenchantment book!" to player
						reduce player's level by 23
						stop
					if player's level is less than 23:
						message "&cError: &4Not enough XP levels!"
						stop
				if arg-1 is "waterbreathingI":
					if player's level is greater than or equal to 23:
						give enchanted book named "&bWater Breathing I" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Helmet||&c- Any Chestplate||&c- Any Leggings||&c- Any Boots" to player
						message "&7&oSucessfully purchased &a&nWater Breathing I&r &7&oenchantment book!" to player
						reduce player's level by 23
						stop
					if player's level is less than 23:
						message "&cError: &4Not enough XP levels!"
						stop
				if arg-1 is "regenerationI":
					if player's level is greater than or equal to 23:
						give enchanted book named "&bRegeneration I" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Helmet||&c- Any Chestplate||&c- Any Leggings||&c- Any Boots" to player
						message "&7&oSucessfully purchased &a&nRegeneration I&r &7&oenchantment book!" to player
						reduce player's level by 23
						stop
					if player's level is less than 23:
						message "&cError: &4Not enough XP levels!"
						stop
				if arg-1 is "speedII":
					if player's level is greater than or equal to 23:
						give enchanted book named "&bSpeed II" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Helmet||&c- Any Chestplate||&c- Any Leggings||&c- Any Boots" to player
						message "&7&oSucessfully purchased &a&nSpeed II&r &7&oenchantment book!" to player
						reduce player's level by 23
						stop
					if player's level is less than 23:
						message "&cError: &4Not enough XP levels!"
						stop
				if arg-1 is "strengthII":
					if player's level is greater than or equal to 23:
						give enchanted book named "&bStrength II" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Helmet||&c- Any Chestplate||&c- Any Leggings||&c- Any Boots" to player
						message "&7&oSucessfully purchased &a&nStrength II&r &7&oenchantment book!" to player
						reduce player's level by 23
						stop
					if player's level is less than 23:
						message "&cError: &4Not enough XP levels!"
						stop
				if arg-1 is "jumpboostII":
					if player's level is greater than or equal to 23:
						give enchanted book named "&bJump Boost II" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Helmet||&c- Any Chestplate||&c- Any Leggings||&c- Any Boots" to player
						message "&7&oSucessfully purchased &a&nJump Boost II&r &7&oenchantment book!" to player
						reduce player's level by 23
						stop
					if player's level is less than 23:
						message "&cError: &4Not enough XP levels!"
						stop
					
# Custom Abilities Purchase

			if {epicenchant.custom.enchants.status} is 1:
				if arg-1 is "gravityI":
					if player's level is greater than or equal to 25:
						give enchanted book named "&aGravity I" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Boots" to player
						message "&7&oSucessfully purchased &a&nGravity I&r &7&oenchantment book!" to player
						reduce player's level by 25
						stop
					if player's level is less than 25:
						message "&cError: &4Not enough XP levels!"
						stop
				if arg-1 is "autorepairI":
					if player's level is greater than or equal to 25:
						give enchanted book named "&aAuto Repair I" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Helmet||&c- Any Chestplate||&c- Any Leggings||&c- Any Boots" to player
						message "&7&oSucessfully purchased &a&nAuto Repair I&r &7&oenchantment book!" to player
						reduce player's level by 25
						stop
					if player's level is less than 25:
						message "&cError: &4Not enough XP levels!"
						stop
				if arg-1 is "autorepairII":
					if player's level is greater than or equal to 35:
						give enchanted book named "&aAuto Repair II" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Helmet||&c- Any Chestplate||&c- Any Leggings||&c- Any Boots" to player
						message "&7&oSucessfully purchased &a&nAuto Repair II&r &7&oenchantment book!" to player
						reduce player's level by 35
						stop
					if player's level is less than 35:
						message "&cError: &4Not enough XP levels!"
						stop
				if arg-1 is "igniteI":
					if player's level is greater than or equal to 25:
						give enchanted book named "&aIgnite I" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Chestplate" to player
						message "&7&oSucessfully purchased &a&nIgnite I&r &7&oenchantment book!" to player
						reduce player's level by 25
						stop
					if player's level is less than 25:
						message "&cError: &4Not enough XP levels!"
						stop
				if arg-1 is "confusionI":
					if player's level is greater than or equal to 25:
						give enchanted book named "&aConfusion I" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Leggings" to player
						message "&7&oSucessfully purchased &a&nConfusion I&r &7&oenchantment book" to player
						reduce player's level by 25
						stop
					if player's level is less than 25:
						message "&cError: &4Not enough XP levels!"
						stop
				if arg-1 is "vampireI":
					if player's level is greater than or equal to 25:
						give enchanted book named "&aVampire I" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Sword||&c- Any Axe" to player
						message "&7&oSucessfully purchased &a&nVampire I&r &7&oenchantment book!" to player
						reduce player's level by 25
						stop
					if player's level is less than 25:
						message "&cError: &4Not enough XP levels!"
						stop
				if arg-1 is "smeltI":
					if player's level is greater than or equal to 25:
						give enchanted book named "&aSmelt I" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Pickaxe||&c- Any Axe||&c- Any Shovel" to player
						message "&7&oSucessfully purchased &a&nSmelt I&r &7&oenchantment book!" to player
						reduce player's level by 25
						stop
					if player's level is less than 25:
						message "&cError: &4Not enough XP levels!"
						stop
				if arg-1 is "smeltII":
					if player's level is greater than or equal to 120:
						give enchanted book named "&aSmelt II" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Pickaxe||&c- Any Axe||&c- Any Shovel" to player
						message "&7&oSucessfully purchased &a&nSmelt II&r &7&oenchantment book!" to player
						reduce player's level by 120
						stop
					if player's level is less than 120:
						message "&cError: &4Not enough XP levels!"
						stop
				if arg-1 is "extinguishI":
					if player's level is greater than or equal to 25:
						give enchanted book named "&aExtinguish I" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Chestplate" to player
						message "&7&oSucessfully purchased &a&nExtinguish I&r &7&oenchantment book!" to player
						reduce player's level by 25
						stop
					if player's level is less than 25:
						message "&cError: &4Not enough XP levels!"
						stop
				
# Active Abilities Purchase

			if {epicenchant.active.enchants.status} is 1:
				if arg-1 is "fireworkI":
					if player's level is greater than or equal to 35:
						give enchanted book named "&4Firework I" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Helmet" to player
						message "&7&oSucessfully purchased &a&nFirework I&r &7&oenchantment book!" to player
						reduce player's level by 35
						stop
					if player's level is less than 35:
						message "&cError: &4Not enough XP levels!"
						stop
				if arg-1 is "vanishI":
					if player's level is greater than or equal to 35:
						give enchanted book named "&4Vanish I" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Helmet" to player
						message "&7&oSucessfully purchased &a&nVanish I&r &7&oenchantment book!" to player
						reduce player's level by 35
						stop
					if player's level is less than 35:
						message "&cError: &4Not enough XP levels!"
						stop
				if arg-1 is "lightningI":
					if player's level is greater than or equal to 35:
						give enchanted book named "&4Lightning I" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Helmet" to player
						message "&7&oSucessfully purchased &a&nLightning I&r &7&oenchantment book!" to player
						reduce player's level by 35
						stop
					if player's level is less than 35:
						message "&cError: &4Not enough XP levels!"
						stop
				if arg-1 is "zoomI":
					if player's level is greater than or equal to 35:
						give enchanted book named "&4Zoom I" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Helmet" to player
						message "&7&oSucessfully purchased &a&nZoom I&r &7&oenchantment book!" to player
						reduce player's level by 35
						stop
					if player's level is less than 35:
						message "&cError: &4Not enough XP levels!"
						stop
				if arg-1 is "invincibleI":
					if player's level is greater than or equal to 35:
						give enchanted book named "&4Invincible I" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Helmet" to player
						message "&7&oSucessfully purchased &a&nInvincible I&r &7&oenchantment book!" to player
						reduce player's level by 35
						stop
					if player's level is less than 35:
						message "&cError: &4Not enough XP levels!"
						stop
				if arg-1 is "projectileI":
					if player's level is greater than or equal to 35:
						give enchanted book named "&4Projectile I" with lore "&7&oRight-click on item with book to apply enchantment.||&r||&7Can Be Applied To&8:||&c- Any Helmet" to player
						message "&7&oSucessfully purchased &a&nProjectile I&r &7&oenchantment book!" to player
						reduce player's level by 35
						stop
					if player's level is less than 35:
						message "&cError: &4Not enough XP levels!"
						stop							
					
		else:
			message "{@main prefix} &cYou do not have permission."
			stop
		
# ---------------------------------------            	
# Application of all enchantments
# ---------------------------------------

on mor.inventory click:
	if cursor item of player is enchanted book:
		if lore of cursor item of player contains "&7&oRight-click on item with book to apply enchantment.":
			if event-item is any sword, any pickaxe, any axe, any shovel, any hoe, bow, any helmet, any chestplate, any leggings or any boots:
				set {_epicenchant.enchantment.identification.%player%::*} to lore of event-item split at "||"
				set {_epicenchant.enchantment.counter.%player%} to 0
				loop {_epicenchant.enchantment.identification.%player%::*}:
					add 1 to {_epicenchant.enchantment.counter.%player%}
				if {_epicenchant.enchantment.counter.%player%} is greater than {@item enchantment limit}:
					cancel event
					message "&cError: &4This item already has {@item enchantment limit} enchantments."
					stop
				else:
					if {epicenchant.potion.enchants.status} is 1:
						if name of cursor item of player contains "Speed":
							if event-item is any boots, any leggings, any chestplate or any helmet:
								if lore of event-item does not contain "Speed":
									cancel event
									set lore of event-item to "%lore of event-item%||%name of cursor item of player%"
									set cursor item of player to air
								else:
									cancel event
									message "&cThis item already contains the enchantment&8: &4Speed"
									stop
						if name of cursor item of player contains "Strength":
							if event-item is any boots, any leggings, any chestplate or any helmet:
								if lore of event-item does not contain "Strength":
									cancel event
									set lore of event-item to "%lore of event-item%||%name of cursor item of player%"
									set cursor item of player to air
								else:
									cancel event
									message "&cThis item already contains the enchantment&8: &4Strength"
									stop
						if name of cursor item of player contains "Jump Boost":
							if event-item is any boots, any leggings, any chestplate or any helmet:
								if lore of event-item does not contain "Jump Boost":
									cancel event
									set lore of event-item to "%lore of event-item%||%name of cursor item of player%"
									set cursor item of player to air
								else:
									cancel event
									message "&cThis item already contains the enchantment&8: &4Jump Boost"
									stop
						if name of cursor item of player contains "Fire Resistance":
							if event-item is any boots, any leggings, any chestplate or any helmet:
								if lore of event-item does not contain "Fire Resistance":
									cancel event
									set lore of event-item to "%lore of event-item%||%name of cursor item of player%"
									set cursor item of player to air
								else:
									cancel event
									message "&cThis item already contains the enchantment&8: &4Fire Resistance"
									stop
						if name of cursor item of player contains "Water Breathing":
							if event-item is any boots, any leggings, any chestplate or any helmet:
								if lore of event-item does not contain "Water Breathing":
									cancel event
									set lore of event-item to "%lore of event-item%||%name of cursor item of player%"
									set cursor item of player to air
								else:
									cancel event
									message "&cThis item already contains the enchantment&8: &4Water Breathing"
									stop
						if name of cursor item of player contains "Regeneration":
							if event-item is any boots, any leggings, any chestplate or any helmet:
								if lore of event-item does not contain "Regeneration":
									cancel event
									set lore of event-item to "%lore of event-item%||%name of cursor item of player%"
									set cursor item of player to air
								else:
									cancel event
									message "&cThis item already contains the enchantment&8: &4Regeneration"
									stop
					if {epicenchant.custom.enchants.status} is 1:
						if name of cursor item of player contains "Gravity":
							if event-item is any boots:
								if lore of event-item does not contain "Gravity":
									cancel event
									set lore of event-item to "%lore of event-item%||%name of cursor item of player%"
									set cursor item of player to air
								else:
									cancel event
									message "&cThis item already contains the enchantment&8: &4Gravity"
									stop
						if name of cursor item of player contains "Auto Repair":
							if event-item is any boots, any leggings, any chestplate or any helmet:
								if lore of event-item does not contain "Auto Repair":
									cancel event
									set lore of event-item to "%lore of event-item%||%name of cursor item of player%"
									set cursor item of player to air
								else:
									cancel event
									message "&cThis item already contains the enchantment&8: &4Auto Repair"
									stop
						if name of cursor item of player contains "Ignite":
							if event-item is any chestplate:
								if lore of event-item does not contain "Ignite":
									cancel event
									set lore of event-item to "%lore of event-item%||%name of cursor item of player%"
									set cursor item of player to air
								else:
									cancel event
									message "&cThis item already contains the enchantment&8: &4Ignite"
									stop
						if name of cursor item of player contains "Confusion":
							if event-item is any leggings:
								if lore of event-item does not contain "Confusion":
									cancel event
									set lore of event-item to "%lore of event-item%||%name of cursor item of player%"
									set cursor item of player to air
								else:
									cancel event
									message "&cThis item already contains the enchantment&8: &4Confusion"
									stop
						if name of cursor item of player contains "Vampire":
							if event-item is any sword or any axe:
								if lore of event-item does not contain "Vampire":
									cancel event
									set lore of event-item to "%lore of event-item%||%name of cursor item of player%"
									set cursor item of player to air
								else:
									cancel event
									message "&cThis item already contains the enchantment&8: &4Confusion"
									stop
						if name of cursor item of player contains "Smelt":
							if event-item is any pickaxe, any axe or any shovel:
								if lore of event-item does not contain "Smelt":
									cancel event
									set lore of event-item to "%lore of event-item%||%name of cursor item of player%"
									set cursor item of player to air
								else:
									cancel event
									message "&cThis item already contains the enchantment&8: &4Smelt"
									stop
						if name of cursor item of player contains "Extinguish":
							if event-item is any chestplate:
								if lore of event-item does not contain "Extinguish":
									cancel event
									set lore of event-item to "%lore of event-item%||%name of cursor item of player%"
									set cursor item of player to air
								else:
									cancel event
									message "&cThis item already contains the enchantment&8: &4Extinguish"
									stop
					if {epicenchant.active.enchants.status} is 1:
						if name of cursor item of player contains "Firework":
							if event-item is any helmet:
								if lore of event-item does not contain "Firework":
									cancel event
									set lore of event-item to "%lore of event-item%||%name of cursor item of player%"
									set cursor item of player to air
								else:
									cancel event
									message "&cThis item already contains the enchantment&8: &4Firework"
									stop
						if name of cursor item of player contains "Vanish":
							if event-item is any helmet:
								if lore of event-item does not contain "Vanish":
									cancel event
									set lore of event-item to "%lore of event-item%||%name of cursor item of player%"
									set cursor item of player to air
								else:
									cancel event
									message "&cThis item already contains the enchantment&8: &4Vanish"
									stop
						if name of cursor item of player contains "Lightning":
							if event-item is any helmet:
								if lore of event-item does not contain "Lightning":
									cancel event
									set lore of event-item to "%lore of event-item%||%name of cursor item of player%"
									set cursor item of player to air
								else:
									cancel event
									message "&cThis item already contains the enchantment&8: &4Lightning"
									stop
						if name of cursor item of player contains "Zoom":
							if event-item is any helmet:
								if lore of event-item does not contain "Zoom":
									cancel event
									set lore of event-item to "%lore of event-item%||%name of cursor item of player%"
									set cursor item of player to air
								else:
									cancel event
									message "&cThis item already contains the enchantment&8: &4Zoom"
									stop
						if name of cursor item of player contains "Invincible":
							if event-item is any helmet:
								if lore of event-item does not contain "Invincible":
									cancel event
									set lore of event-item to "%lore of event-item%||%name of cursor item of player%"
									set cursor item of player to air
								else:
									cancel event
									message "&cThis item already contains the enchantment&8: &4Invincible"
									stop
						if name of cursor item of player contains "Projectile":
							if event-item is any helmet:
								if lore of event-item does not contain "Projectile":
									cancel event
									set lore of event-item to "%lore of event-item%||%name of cursor item of player%"
									set cursor item of player to air
								else:
									cancel event
									message "&cThis item already contains the enchantment&8: &4Projectile"
									stop
			
# Potion effects application 
# ---------------------------------------						

sharpsk on armor equip:
	if lore of event-item contains "Speed I":
		remove speed from player
		apply speed to player for 999 days
	if lore of event-item contains "Speed II":
		remove speed from player
		apply speed 2 to player for 999 days
	if lore of event-item contains "Strength I":
		remove strength from player
		apply strength to player for 999 days
	if lore of event-item contains "Strength II":
		remove strength from player
		apply strength 2 to player for 999 days
	if lore of event-item contains "Jump Boost I":
		remove jump from player
		apply jump to player for 999 days
	if lore of event-item contains "Jump Boost II":
		remove jump from player
		apply jump 2 to player for 999 days
	if lore of event-item contains "Fire Resistance I":
		remove fire resistance from player
		apply fire resistance to player for 999 days
	if lore of event-item contains "Water Breathing I":
		remove water breathing from player
		apply water breathing to player for 999 days
	if lore of event-item contains "Regeneration I":
		remove regeneration from player
		apply regeneration to player for 999 days

sharpsk on armor unequip:
	if lore of event-item contains "Speed I":
		remove speed from player
	if lore of event-item contains "Speed II":
		remove speed from player
	if lore of event-item contains "Strength I":
		remove strength from player
	if lore of event-item contains "Strength II":
		remove strength from player
	if lore of event-item contains "Jump Boost I":
		remove jump from player
	if lore of event-item contains "Jump Boost II":
		remove jump from player
	if lore of event-item contains "Fire Resistance I":
		remove fire resistance from player
	if lore of event-item contains "Water Breathing I":
		remove water breathing from player
	if lore of event-item contains "Regeneration I":
		remove regeneration from player
		
# ---------------------------------------            	
# Active Abilities
# ---------------------------------------

every 3 seconds:
	if {epicenchant.active.enchants.status} is 1:
		loop all players:
			if loop-player's helmet is not set:
				delete {epicenchant.a.ability.%loop-player%}
				set {epicenchant.ability.activation.status.%loop-player%} to "&cCurrently Inactive"
on load:
	loop {uuidName::*}:
		delete {epicenchant.a.ability.allowswitch.%loop-value%}
		wait 1 second
		delete {epicenchant.a.ability.activation.status.%loop-value%}
command /ability:
	trigger:
		if {epicenchant.active.enchants.status} is 1:
			if player has permission "{@general permission}":
				if {epicenchant.a.ability.allowswitch.%player%} is not set:
					set {epicenchant.a.ability.allowswitch.%player%} to 0
				if {epicenchant.a.ability.allowswitch.%player%} is 0:
					if lore of player's helmet does not contain "Firework I" or "Vanish I" or "Lightning I" or "Zoom I" or "Invincible I" or "Projectile I":
						set {epicenchant.a.ability.activation.status.%player%} to "&cCurrently Inactive"
						delete {epicenchant.a.ability.%player%}
					wait 3 tick
					open chest with 4 rows named "&c&lActive Ability Selection" to player
					if name of player's current inventory contains "&c&lActive Ability Selection":
						format slot 35 of player with skull of ("%player%" parsed as offline player) named "&3&lCurrent Ability" with lore "&b%{epicenchant.a.ability.activation.status.%player%}%" to be unstealable
						format slot 34 of player with barrier named "&c&lDisable Abilities" with lore "&4Disable the current active ability that you are using." to close then run [execute player command "abilityactivate disable"]
						if lore of player's helmet contains "Projectile I":
							format slot 5 of player with a arrow named "&2&lProjectile I &8-&r &a&lAbility" with lore "&3&oAbility to travel like a projectile.||&c3 minute cooldown" to close then run [execute player command "abilityactivate projectile"]
						if lore of player's helmet does not contain "Projectile I":
							format slot 5 of player with red stained glass pane named "&2&lProjectile I &8-&r &c&lAbility" with lore "&4This ability is currently not available." to be unstealable
						if lore of player's helmet contains "Invincible I":
							format slot 4 of player with a enchanted golden apple named "&d&lInvincible I &8-&r &a&lAbility" with lore "&3&oAbility to temporarily be immune to all damage for 5 seconds.||&c5 minute cooldown" to close then run [execute player command "abilityactivate invincible"]
						if lore of player's helmet does not contain "Invincible I":
							format slot 4 of player with red stained glass pane named "&d&lInvincible I &8-&r &c&lAbility" with lore "&4This ability is currently not available." to be unstealable
						if lore of player's helmet contains "Zoom I":
							format slot 3 of player with a compass named "&b&lZoom I &8-&r &a&lAbility" with lore "&3&oAbility to travel faster than sound for 2 seconds.||&c5 minute cooldown" to close then run [execute player command "abilityactivate zoom"]
						if lore of player's helmet does not contain "Zoom I":
							format slot 3 of player with red stained glass pane named "&b&lZoom I &8-&r &c&lAbility" with lore "&4This ability is currently not available." to be unstealable
						if lore of player's helmet contains "Lightning I":
							format slot 2 of player with a nether star named "&e&lLightning I &8-&r &a&lAbility" with lore "&3&oAbility to strike the surrounding mobs and players with lightning.||&c3 minute cooldown" to close then run [execute player command "abilityactivate lightning"]
						if lore of player's helmet does not contain "Lightning I":
							format slot 2 of player with red stained glass pane named "&e&lLightning I &8-&r &c&lAbility" with lore "&4This ability is currently not available." to be unstealable						
						if lore of player's helmet contains "Vanish I":
							format slot 1 of player with a golden carrot named "&9&lVanish I &8-&r &a&lAbility" with lore "&3&oAbility to go invisible for 5 seconds.||&c5 minute cooldown" to close then run [execute player command "abilityactivate vanish"]
						if lore of player's helmet does not contain "Vanish I":
							format slot 1 of player with red stained glass pane named "&9&lVanish I &8-&r &c&lAbility" with lore "&4This ability is currently not available." to be unstealable
						if lore of player's helmet contains "Firework I":
							format slot 0 of player with a firework rocket named "&6&lFirework I &8-&r &a&lAbility" with lore "&3&oAbility to blast in the air.||&c3 minute cooldown" to close then run [execute player command "abilityactivate firework"]
						if lore of player's helmet does not contain "Firework I":
							format slot 0 of player with red stained glass pane named "&6&lFirework I &8-&r &c&lAbility" with lore "&4This ability is currently not available." to be unstealable
						loop integers between 0 and 35:
							if slot loop-integer of player's current inventory is air:
								format slot loop-integer of player with white stained glass pane named "&r" with lore "&r" to be unstealable
						
				else:
					message "{@abilities prefix} &cYou must wait until your last ability cooldown is finished!"
					stop
			else:
				message "{@main prefix} &cYou do not have permission."
				stop
			

command /abilityactivate [<text>]:
	trigger:
		if {epicenchant.active.enchants.status} is 1:
			if player has permission "{@general permission}":	
				if {epicenchant.a.ability.allowswitch.%player%} is 0:
					if arg-1 is "firework":
						if lore of player's helmet contains "Firework I":
							if {epicenchant.a.ability.%player%} is "firework":
								message "{@abilities prefix} &cThat ability is already currently active!"
								stop
							else:
								message "{@abilities prefix} &aFirework ability has been activated!"
								set {epicenchant.a.ability.%player%} to "firework"
								set {epicenchant.a.ability.activation.status.%player%} to "Firework"
								stop
					if arg-1 is "vanish":
						if lore of player's helmet contains "Vanish I":
							if {epicenchant.a.ability.%player%} is "vanish":
								message "{@abilities prefix} &cThat ability is already currently active!"
								stop
							else:
								message "{@abilities prefix} &aVanish ability has been activated!"
								set {epicenchant.a.ability.%player%} to "vanish"
								set {epicenchant.a.ability.activation.status.%player%} to "Vanish"
								stop
					if arg-1 is "lightning":
						if lore of player's helmet contains "Lightning I":
							if {epicenchant.a.ability.%player%} is "lightning":
								message "{@abilities prefix} &cThat ability is already currently active!"
								stop
							else:
								message "{@abilities prefix} &aLightning ability has been activated!"
								set {epicenchant.a.ability.%player%} to "lightning"
								set {epicenchant.a.ability.activation.status.%player%} to "Lightning"
								stop
					if arg-1 is "zoom":
						if lore of player's helmet contains "Zoom I":
							if {epicenchant.a.ability.%player%} is "zoom":
								message "{@abilities prefix} &cThat ability is already currently active!"
								stop
							else:
								message "{@abilities prefix} &aZoom ability has been activated!"
								set {epicenchant.a.ability.%player%} to "zoom"
								set {epicenchant.a.ability.activation.status.%player%} to "Zoom"
								stop
					if arg-1 is "invincible":
						if lore of player's helmet contains "Invincible I":
							if {epicenchant.a.ability.%player%} is "invincible":
								message "{@abilities prefix} &cThat ability is already currently active!"
								stop
							else:
								message "{@abilities prefix} &aInvincible ability has been activated!"
								set {epicenchant.a.ability.%player%} to "invincible"
								set {epicenchant.a.ability.activation.status.%player%} to "Invincible"
								stop
					if arg-1 is "projectile":
						if lore of player's helmet contains "Projectile I":
							if {epicenchant.a.ability.%player%} is "projectile":
								message "{@abilities prefix} &cThat ability is already currently active!"
								stop
							else:
								message "{@abilities prefix} &aProjectile ability has been activated!"
								set {epicenchant.a.ability.%player%} to "projectile"
								set {epicenchant.a.ability.activation.status.%player%} to "Projectile"
								stop
					if arg-1 is "disable":
						if {epicenchant.a.ability.%player%} is set:
							message "{@abilities prefix} &cCurrent ability has been deactivated!"
							set {epicenchant.a.ability.activation.status.%player%} to "&cCurrently Inactive"
							delete {epicenchant.a.ability.%player%} 
							stop
						else:
							message "{@abilities prefix} &cYou currently do not have any active abilities!"
							stop
				else:
					message "{@abilities prefix} &cYou must wait until your last ability cooldown is finished!"
					stop
			else:
				message "{@main prefix} &cYou do not have permission."
				stop
				
on left-click:
	if {epicenchant.active.enchants.status} is 1:
		if player has permission "{@general permission}":
			if player's tool is air:
				if {epicenchant.a.ability.%player%} is "firework":
					if lore of player's helmet contains "Firework I":
						set {_epicenchant.a.ability.firework.cooldown.waited.%player%} to difference between {epicenchant.a.ability.firework.cooldown.%player%} and now
						if {_epicenchant.a.ability.firework.cooldown.waited.%player%} is less than 3 minutes:
							stop
						else:
							set {epicenchant.a.ability.firework.cooldown.%player%} to now
							set {epicenchant.a.ability.allowswitch.%player%} to 1
							set {epicenchant.a.ability.firework.nofalldamage.%player%} to 1
							push player up at speed 1.5
							wait 3 minute
							set {epicenchant.a.ability.allowswitch.%player%} to 0
							if {epicenchant.a.ability.%player%} is set:
								if lore of player's helmet contains "Firework I":
									if {epicenchant.a.ability.firework.cooldown.%player%} is set:
										message ""
										message "{@abilities prefix} &9Cooldown has expired!"
										message "{@abilities prefix} &aFirework ability activated!"
										message ""
										stop
				if {epicenchant.a.ability.%player%} is "vanish":
					if lore of player's helmet contains "Vanish I":
						set {_epicenchant.a.ability.vanish.cooldown.waited.%player%} to difference between {epicenchant.a.ability.vanish.cooldown.%player%} and now
						if {_epicenchant.a.ability.vanish.cooldown.waited.%player%} is less than 5 minutes:
							stop
						else:
							set {epicenchant.a.ability.vanish.cooldown.%player%} to now
							set {epicenchant.a.ability.allowswitch.%player%} to 1
							message "{@abilities prefix} &aYou have been vanished for 5 seconds!"
							hide the player from all players
							apply invisibility 2 to player for 5 seconds
							wait 5 seconds
							message "{@abilities prefix} &aYou have been unvanished!"
							reveal the player from all players
							wait 5 minutes and 5 seconds
							set {epicenchant.a.ability.allowswitch.%player%} to 0
							if {epicenchant.a.ability.%player%} is set:
								if lore of player's helmet contains "Vanish I":
									if {epicenchant.a.ability.vanish.cooldown.%player%} is set:
										message ""
										message "{@abilities prefix} &9Cooldown has expired!"
										message "{@abilities prefix} &aVanish ability activated!"
										message ""
										stop
				if {epicenchant.a.ability.%player%} is "lightning":
					if lore of player's helmet contains "Lightning I":
						set {_epicenchant.a.ability.lightning.cooldown.waited.%player%} to difference between {epicenchant.a.ability.lightning.cooldown.%player%} and now
						if {_epicenchant.a.ability.lightning.cooldown.waited.%player%} is less than 3 minutes:
							stop
						else:
							set {epicenchant.a.ability.lightning.cooldown.%player%} to now
							set {epicenchant.a.ability.allowswitch.%player%} to 1
							loop all entities in radius 5 of player:
								if loop-entity is not player:
									strike lightning at loop-entity
							message "{@abilities prefix} &aZAP!"
							wait 3 minutes
							set {epicenchant.a.ability.allowswitch.%player%} to 0
							if {epicenchant.a.ability.%player%} is set:
								if lore of player's helmet contains "Lightning I":
									if {epicenchant.a.ability.lightning.cooldown.%player%} is set:
										message ""
										message "{@abilities prefix} &9Cooldown has expired!"
										message "{@abilities prefix} &aLightning ability activated!"
										message ""
										stop
				if {epicenchant.a.ability.%player%} is "zoom":
					if lore of player's helmet contains "Zoom I":
						set {_epicenchant.a.ability.zoom.cooldown.waited.%player%} to difference between {epicenchant.a.ability.zoom.cooldown.%player%} and now
						if {_epicenchant.a.ability.zoom.cooldown.waited.%player%} is less than 5 minutes:
							stop
						else:
							set {epicenchant.a.ability.zoom.cooldown.%player%} to now
							set {epicenchant.a.ability.allowswitch.%player%} to 1 
							set player's walking speed to 2
							wait 2 seconds
							reset player's walking speed
							wait 5 minutes and 2 seconds
							set {epicenchant.a.ability.allowswitch.%player%} to 0
							if {epicenchant.a.ability.%player%} is set:
								if lore of player's helmet contains "Zoom I":
									if {epicenchant.a.ability.zoom.cooldown.%player%} is set:
										message ""
										message "{@abilities prefix} &9Cooldown has expired!"
										message "{@abilities prefix} &aZoom ability activated!"
										message ""
										stop
				if {epicenchant.a.ability.%player%} is "invincible":
					if lore of player's helmet contains "Invincible I":
						set {_epicenchant.a.ability.invincible.cooldown.waited.%player%} to difference between {epicenchant.a.ability.invincible.cooldown.%player%} and now
						if {_epicenchant.a.ability.invincible.cooldown.waited.%player%} is less than 5 minutes:
							stop
						else:
							message "{@abilities prefix} &aYou have been turned invincible for 5 seconds."
							set {epicenchant.a.ability.invincible.cooldown.%player%} to now
							set {epicenchant.a.ability.allowswitch.%player%} to 1 
							set {epicenchant.a.ability.invincible.nodamage.%player%} to 1
							drawComplexCircle particle "redstone", RGB 255, 223, 0, center player, id "%player%-ability.invincible1", randomRotation true, radius .8, density 20, start 0, visibleRange 35, xRotation 23, yRotation 120, zRotation 0
							drawComplexCircle particle "redstone", RGB 255, 223, 0, center player, id "%player%-ability.invincible2", randomRotation false, radius .8, density 20, start 0, visibleRange 35, xRotation 23, yRotation 10, zRotation 0
							drawComplexCircle particle "redstone", RGB 255, 223, 0, center player, id "%player%-ability.invincible3", randomRotation false, radius .8, density 20, start 0, visibleRange 35, xRotation 0, yRotation 60, zRotation 0
							drawComplexCircle particle "redstone", RGB 255, 223, 0, center player, id "%player%-ability.invincible4", randomRotation true, radius .8, density 20, start 0, visibleRange 35, xRotation 25, yRotation 54, zRotation 0
							wait 5 seconds
							stopEffect id "%player%-ability.invincible1"
							stopEffect id "%player%-ability.invincible2"
							stopEffect id "%player%-ability.invincible3"
							stopEffect id "%player%-ability.invincible4"
							message "{@abilities prefix} &AYou are no longer invincible."
							set {epicenchant.a.ability.invincible.nodamage.%player%} to 0
							wait 5 minutes and 5 seconds
							set {epicenchant.a.ability.allowswitch.%player%} to 0
							if {epicenchant.a.ability.%player%} is set:
								if lore of player's helmet contains "Invincible I":
									if {epicenchant.a.ability.zoom.cooldown.%player%} is set:
										message ""
										message "{@abilities prefix} &9Cooldown has expired!"
										message "{@abilities prefix} &aInvincible ability activated!"
										message ""
										stop
				if {epicenchant.a.ability.%player%} is "projectile":
					if lore of player's helmet contains "Projectile I":
						set {_epicenchant.a.ability.projectile.cooldown.waited.%player%} to difference between {epicenchant.a.ability.projectile.cooldown.%player%} and now
						if {_epicenchant.a.ability.projectile.cooldown.waited.%player%} is less than 3 minutes:
							stop
						else:
							set {epicenchant.a.ability.projectile.cooldown.%player%} to now
							set {epicenchant.a.ability.allowswitch.%player%} to 1
							set {epicenchant.a.ability.projectile.nofalldamage.%player%} to 1
							push player upwards at speed 1.5
							push player forwards at speed 1
							wait 10 ticks
							push player forwards at speed 2
							wait 10 tick
							push player forwards at speed 1
							push player downwards at speed 0.5
							wait 3 minute
							set {epicenchant.a.ability.allowswitch.%player%} to 0
							if {epicenchant.a.ability.%player%} is set:
								if lore of player's helmet contains "Projectile I":
									if {epicenchant.a.ability.firework.cooldown.%player%} is set:
										message ""
										message "{@abilities prefix} &9Cooldown has expired!"
										message "{@abilities prefix} &aProjectile ability activated!"
										message ""
										stop
			
on damage:
	if victim is a player:
		if {epicenchant.active.enchants.status} is 1:
			if {epicenchant.a.ability.firework.nofalldamage.%victim%} is 1:
				if damage is caused by fall:
					cancel event
					set {epicenchant.a.ability.firework.nofalldamage.%victim%} to 0
					stop
			if {epicenchant.a.ability.projectile.nofalldamage.%victim%} is 1:
				if damage is caused by fall:
					cancel event
					set {epicenchant.a.ability.projectile.nofalldamage.%victim%} to 0
					stop
			if {epicenchant.a.ability.invincible.nodamage.%victim%} is 1:
				cancel event
				stop 
			
# ----------------------------------------------------------------------------------------------------------------------------------------------            	
# Custom Abilities
# ----------------------------------------------------------------------------------------------------------------------------------------------

# ---------------------------------------            	
# Gravity
# ---------------------------------------    

on death:
	if {epicenchant.custom.enchants.status} is 1:
		if lore of victim's boots contains "Gravity I":
			loop all entities in radius 7 of player:
				if loop-entity is a player:
					push loop-entity up at speed 1.5
				if loop-entity is not a player:
					push loop-entity up at speed 2.5
				stop

# ---------------------------------------            	
# Auto Repair
# ---------------------------------------    

every 20 seconds:
	if {epicenchant.custom.enchants.status} is 1:
		loop all players:
			if lore of loop-player's boots contains "Auto Repair I":
				remove 1 from durability of loop-player's boots
			if lore of loop-player's leggings contains "Auto Repair I":
				remove 1 from durability of loop-player's leggings
			if lore of loop-player's chestplate contains "Auto Repair I":
				remove 1 from durability of loop-player's chestplate
			if lore of loop-player's helmet contains "Auto Repair I":
				remove 1 from durability of loop-player's helmet
			if lore of loop-player's boots contains "Auto Repair 2":
				remove 2 from durability of loop-player's boots
			if lore of loop-player's leggings contains "Auto Repair 2":
				remove 2 from durability of loop-player's leggings
			if lore of loop-player's chestplate contains "Auto Repair 2":
				remove 2 from durability of loop-player's chestplate
			if lore of loop-player's helmet contains "Auto Repair 2":
				remove 2 from durability of loop-player's helmet
			stop

# ---------------------------------------            	
# Ignite
# ---------------------------------------   

on damage:
	if victim is a player:
		if attacker is a player:
			if {epicenchant.custom.enchants.status} is 1:
				if lore of victim's chestplate contains "Ignite I":
					if {epicenchant.c.ability.ignite.status.%attacker%} is not set:
						set {epicenchant.c.ability.ignite.status.%attacker%} to 0
					if {epicenchant.c.ability.ignite.status.%attacker%} is 0:
						set {epicenchant.c.ability.ignite.chance.%victim%} to a random integer between 0 and 35
						if {epicenchant.c.ability.ignite.chance.%victim%} is less than or equal to {@ignite percentage chance}:
							message "{@main prefix} &cYou have been ignited by your victim!" to attacker
							set {epicenchant.c.ability.ignite.status.%attacker%} to 1
							loop 5 times:
								wait 2 second
								drawDot count 15, particle "flame", XYZ 0.5, 1, 0.5, center attacker, visibleRange 320, pulseDelay 0, keepFor 10 ticks
								if lore of attacker's chestplate contains "Extinguish I":
									damage attacker by 0.5 heart
								else:
									damage attacker by 1 heart
							set {epicenchant.c.ability.ignite.status.%attacker%} to 0
							stop
							
# ---------------------------------------            	
# Confusion
# ---------------------------------------   

on damage:
	if victim is a player:
		if attacker is a player:
			if {epicenchant.custom.enchants.status} is 1:
				if lore of victim's leggings contains "Confusion I":
					if {epicenchant.c.ability.confusion.status.%attacker%} is not set:
						set {epicenchant.c.ability.confusion.status.%attacker%} to 0
					if {epicenchant.c.ability.confusion.status.%attacker%} is 0:
						set {epicenchant.c.ability.confusion.chance.%victim%} to a random number between 0 and 35
						if {epicenchant.c.ability.confusion.chance.%victim%} is less than or equal to {@confusion percentage chance}:
							message "{@main prefix} &cYou have been put in a state of confusion by your victim." to attacker
							message "{@main prefix} &cYour attacker has been confused." to victim
							set {epicenchant.c.ability.confusion.status.%attacker%} to 1
							apply slowness 3 to attacker for 5 seconds
							apply blindness 10 to attacker for 5 seconds
							set victim's walking speed to 2
							wait 2 seconds
							reset victim's walking speed
							set {epicenchant.c.ability.confusion.status.%attacker%} to 0
							stop					
				
# ---------------------------------------            	
# Vampire 
# ---------------------------------------   

on damage:
	if victim is a player:
		if attacker is a player:
			if {epicenchant.custom.enchants.status} is 1:
				if lore of attacker's tool contains "Vampire I":
					set {epicenchant.c.ability.vampire.chance.%attacker%} to a random number between 0 and 35
					if {epicenchant.c.ability.vampire.chance.%attacker%} is less than or equal to {@vampire percentage chance}:
						message "{@main prefix} &cYou have stole one heart from your victim!" to attacker
						damage victim by 1 heart
						add 1 to attacker's health
						stop
						
# ---------------------------------------            	
# Smelt 
# ---------------------------------------   

on mine:
	if {epicenchant.custom.enchants.status} is 1:
		if lore of player's tool contains "Smelt I":
			if player's gamemode is survival:
				set {epicenchant.c.ability.smelt.chance.%player%} to random number between 0 and 35
				if {epicenchant.c.ability.smelt.chance.%player%} is less than or equal to {@smelt percentage chance}:
					if player's tool is any pickaxe, any axe or any shovel:
						if event-block is log:
							cancel event
							set {_epicenchant.c.ability.smelt.particle} to location of event-block
							drawDot count 5, particle "flame", XYZ 0.5, 1, 0.5, center {_epicenchant.c.ability.smelt.particle}, visibleRange 320, pulseDelay 0, keepFor 5 ticks
							set event-block to air
							give player 1 charcoal
							stop
						if event-block is cobblestone:
							cancel event
							set {_epicenchant.c.ability.smelt.particle} to location of event-block
							drawDot count 5, particle "flame", XYZ 0.5, 1, 0.5, center {_epicenchant.c.ability.smelt.particle}, visibleRange 320, pulseDelay 0, keepFor 5 ticks
							set event-block to air
							give player 1 stone
							stop
						if event-block is sand:
							cancel event
							set {_epicenchant.c.ability.smelt.particle} to location of event-block
							drawDot count 5, particle "flame", XYZ 0.5, 1, 0.5, center {_epicenchant.c.ability.smelt.particle}, visibleRange 320, pulseDelay 0, keepFor 5 ticks
							set event-block to air
							give player 1 glass
							stop
						if event-block is cactus:
							cancel event
							set {_epicenchant.c.ability.smelt.particle} to location of event-block
							drawDot count 5, particle "flame", XYZ 0.5, 1, 0.5, center {_epicenchant.c.ability.smelt.particle}, visibleRange 320, pulseDelay 0, keepFor 5 ticks
							set event-block to air
							give player 1 green dye
							stop
						if event-block is iron ore:
							cancel event
							set {_epicenchant.c.ability.smelt.particle} to location of event-block
							drawDot count 5, particle "flame", XYZ 0.5, 1, 0.5, center {_epicenchant.c.ability.smelt.particle}, visibleRange 320, pulseDelay 0, keepFor 5 ticks
							set event-block to air
							give player 1 iron ingot
							stop
						if event-block is gold ore:
							cancel event
							set {_epicenchant.c.ability.smelt.particle} to location of event-block
							drawDot count 5, particle "flame", XYZ 0.5, 1, 0.5, center {_epicenchant.c.ability.smelt.particle}, visibleRange 320, pulseDelay 0, keepFor 5 ticks
							set event-block to air
							give player 1 gold ingot
							stop
		if lore of player's tool contains "Smelt II":
			if event-block is log:
				cancel event
				set {_epicenchant.c.ability.smelt.particle} to location of event-block
				drawDot count 5, particle "flame", XYZ 0.5, 1, 0.5, center {_epicenchant.c.ability.smelt.particle}, visibleRange 320, pulseDelay 0, keepFor 5 ticks
				set event-block to air
				give player 1 charcoal
				stop
			if event-block is cobblestone:
				cancel event
				set {_epicenchant.c.ability.smelt.particle} to location of event-block
				drawDot count 5, particle "flame", XYZ 0.5, 1, 0.5, center {_epicenchant.c.ability.smelt.particle}, visibleRange 320, pulseDelay 0, keepFor 5 ticks
				set event-block to air
				give player 1 stone
				stop
			if event-block is sand:
				cancel event
				set {_epicenchant.c.ability.smelt.particle} to location of event-block
				drawDot count 5, particle "flame", XYZ 0.5, 1, 0.5, center {_epicenchant.c.ability.smelt.particle}, visibleRange 320, pulseDelay 0, keepFor 5 ticks
				set event-block to air
				give player 1 glass
				stop
			if event-block is cactus:
				cancel event
				set {_epicenchant.c.ability.smelt.particle} to location of event-block
				drawDot count 5, particle "flame", XYZ 0.5, 1, 0.5, center {_epicenchant.c.ability.smelt.particle}, visibleRange 320, pulseDelay 0, keepFor 5 ticks
				set event-block to air
				give player 1 green dye
				stop
			if event-block is iron ore:
				cancel event
				set {_epicenchant.c.ability.smelt.particle} to location of event-block
				drawDot count 5, particle "flame", XYZ 0.5, 1, 0.5, center {_epicenchant.c.ability.smelt.particle}, visibleRange 320, pulseDelay 0, keepFor 5 ticks
				set event-block to air
				give player 1 iron ingot
				stop
			if event-block is gold ore:
				cancel event
				set {_epicenchant.c.ability.smelt.particle} to location of event-block
				drawDot count 5, particle "flame", XYZ 0.5, 1, 0.5, center {_epicenchant.c.ability.smelt.particle}, visibleRange 320, pulseDelay 0, keepFor 5 ticks
				set event-block to air
				give player 1 gold ingot
				stop		